// This file is autogenerated. Changes will be overwritten.
#include <YPKJ5OE7LN/moc_algorithm_input_dialog.cpp>
#include <YPKJ5OE7LN/moc_code_generator_dialog.cpp>
#include <YPKJ5OE7LN/moc_color_legend_panel.cpp>
#include <YPKJ5OE7LN/moc_control_panel.cpp>
#include <YPKJ5OE7LN/moc_main_window.cpp>
#include <YPKJ5OE7LN/moc_metrics_panel.cpp>
#include <YPKJ5OE7LN/moc_structure_selector.cpp>
#include <YPKJ5OE7LN/moc_toolbox_panel.cpp>
#include <YPKJ5OE7LN/moc_tutorial_overlay.cpp>
#include <YPKJ5OE7LN/moc_visualization_pane.cpp>
#include <FUF3DDMRNR/moc_playback_controller.cpp>
#include <FUF3DDMRNR/moc_visualization_renderer.cpp>
